### ISSUE TITLE
Suddenly can't install ESMPack

### ISSUE THREAD

**Issue by Gryphire** [wviechtb/esmpack#3]
I actually have the same (but also a slightly different) issue. I've been running my script in which ESMPack is used for a while now (last time was end of August) but all of a sudden when I tried to run the script today it started giving me a strange error that the package wasn't installed, and when installing via "remotes::install_github("wviechtb/esmpack")" I get the following (see screenshot):

<img width="441" alt="Screenshot 2021-10-21 at 11 42 36" src="https://user-images.githubusercontent.com/17269537/138252964-3f055226-e16e-416b-9498-263337514a2c.png">

So it's the same problem (not being able to install ESMPack) but seemingly for a different reason.

_Originally posted by @Gryphire in https://github.com/wviechtb/esmpack/issues/2#issuecomment-948439213_

**Comment by wviechtb** [comment]
I don't really know what the issue is. I again tried under both Linux and Windows. For example, for the latter:

    > sessionInfo()
    R version 4.1.1 (2021-08-10)
    Platform: x86_64-w64-mingw32/x64 (64-bit)
    Running under: Windows 7 x64 (build 7601) Service Pack 1
    
    Matrix products: default
    
    locale:
    [1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
    [3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
    [5] LC_TIME=English_United States.1252    
    
    attached base packages:
    [1] stats     graphics  grDevices utils     datasets  methods   base     
    
    loaded via a namespace (and not attached):
    [1] compiler_4.1.1 tools_4.1.1   
    
    > remotes::install_github("wviechtb/esmpack")
    Downloading GitHub repo wviechtb/esmpack@HEAD
    Running `R CMD build`...
    * checking for file 'C:\Users\wvb\AppData\Local\Temp\Rtmp2PFDWw\remotes53851046e54\wviechtb-esmpack-e40dedb/DESCRIPTION' ... OK
    * preparing 'esmpack':
    * checking DESCRIPTION meta-information ... OK
    * checking for LF line-endings in source and make files and shell scripts
    * checking for empty or unneeded directories
    Omitted 'LazyData' from DESCRIPTION
    * building 'esmpack_0.1-17.tar.gz'
    Installing package into ‘C:/Users/wvb/Documents/R/win-library/4.1’
    (as ‘lib’ is unspecified)
    * installing *source* package 'esmpack' ...
    ** using staged installation
    ** R
    ** byte-compile and prepare package for lazy loading
    ** help
    *** installing help indices
      converting help for package 'esmpack'
        finding HTML links ... done
        aggreg                                  html  
        calc.mcent                              html  
        calc.mean                               html  
        calc.nomiss                             html  
        check.nodup                             html  
        check.nomiss                            html  
        check.timeinvar                         html  
        combitems                               html  
        esmpack-package                         html  
        get.beep.number                         html  
        get.day.number                          html  
        get.timeinvar                           html  
        lagvar                                  html  
        mvvar                                   html  
        nsub                                    html  
        rename                                  html  
    ** building package indices
    ** testing if installed package can be loaded from temporary location
    *** arch - i386
    *** arch - x64
    ** testing if installed package can be loaded from final location
    *** arch - i386
    *** arch - x64
    ** testing if installed package keeps a record of temporary installation path
    * DONE (esmpack)

So, works without problems. Searching for the `Using github PAT ...` message led me to:

https://community.rstudio.com/t/troubleshooting-github-tokens/115489

Maybe this helps you resolve the issue?
